/* ============================================================================
   04a - Batch Scoring via Model Registry (Warehouse Inference)
   ----------------------------------------------------------------------------
   Model: CLIK_WORKSHOP2.PUBLIC.CLIK_PD_MODEL  (default version V2_SNOWPARK_ML)

   PENTING: model dilatih dengan fitur hasil One-Hot Encoding (Snowpark ML),
   sehingga method PREDICT_PROBA mengharapkan 60 fitur ter-encode DALAM URUTAN
   tertentu (lihat SHOW FUNCTIONS IN MODEL ...). Kita reproduksi encoding itu
   di SQL: OHE untuk GENDER/EMPLOYMENT_TYPE/EDUCATION/REGION_CODE + derived
   DTI_RATIO = MONTHLY_INSTALLMENT / MONTHLY_INCOME.

   Output PREDICT_PROBA berupa OBJECT dengan key:
     PREDICT_PROBA_0 = P(tidak default), PREDICT_PROBA_1 = P(default) = PD score.
   ============================================================================ */
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE GEN2_SMALL;
USE DATABASE CLIK_WORKSHOP2;
USE SCHEMA PUBLIC;

-- View helper: SUBJECT_FEATURES -> 60 fitur ter-encode sesuai signature model.
CREATE OR REPLACE VIEW SUBJECT_FEATURES_ENCODED AS
SELECT
    SUBJECT_ID,
    IFF(GENDER='F',1,0)::FLOAT AS GENDER_F,
    IFF(GENDER='M',1,0)::FLOAT AS GENDER_M,
    IFF(EMPLOYMENT_TYPE='Freelance',1,0)::FLOAT   AS EMPLOYMENT_TYPE_FREELANCE,
    IFF(EMPLOYMENT_TYPE='Karyawan',1,0)::FLOAT    AS EMPLOYMENT_TYPE_KARYAWAN,
    IFF(EMPLOYMENT_TYPE='PNS',1,0)::FLOAT         AS EMPLOYMENT_TYPE_PNS,
    IFF(EMPLOYMENT_TYPE='Profesional',1,0)::FLOAT AS EMPLOYMENT_TYPE_PROFESIONAL,
    IFF(EMPLOYMENT_TYPE='Wiraswasta',1,0)::FLOAT  AS EMPLOYMENT_TYPE_WIRASWASTA,
    IFF(EDUCATION='D3',1,0)::FLOAT  AS EDUCATION_D3,
    IFF(EDUCATION='S1',1,0)::FLOAT  AS EDUCATION_S1,
    IFF(EDUCATION='S2',1,0)::FLOAT  AS EDUCATION_S2,
    IFF(EDUCATION='SD',1,0)::FLOAT  AS EDUCATION_SD,
    IFF(EDUCATION='SMA',1,0)::FLOAT AS EDUCATION_SMA,
    IFF(REGION_CODE='BALI',1,0)::FLOAT    AS REGION_CODE_BALI,
    IFF(REGION_CODE='BANTEN',1,0)::FLOAT  AS REGION_CODE_BANTEN,
    IFF(REGION_CODE='DKI',1,0)::FLOAT     AS REGION_CODE_DKI,
    IFF(REGION_CODE='JABAR',1,0)::FLOAT   AS REGION_CODE_JABAR,
    IFF(REGION_CODE='JATENG',1,0)::FLOAT  AS REGION_CODE_JATENG,
    IFF(REGION_CODE='JATIM',1,0)::FLOAT   AS REGION_CODE_JATIM,
    IFF(REGION_CODE='KALBAR',1,0)::FLOAT  AS REGION_CODE_KALBAR,
    IFF(REGION_CODE='KALTIM',1,0)::FLOAT  AS REGION_CODE_KALTIM,
    IFF(REGION_CODE='LAMPUNG',1,0)::FLOAT AS REGION_CODE_LAMPUNG,
    IFF(REGION_CODE='MALUKU',1,0)::FLOAT  AS REGION_CODE_MALUKU,
    IFF(REGION_CODE='NTB',1,0)::FLOAT     AS REGION_CODE_NTB,
    IFF(REGION_CODE='PAPUA',1,0)::FLOAT   AS REGION_CODE_PAPUA,
    IFF(REGION_CODE='RIAU',1,0)::FLOAT    AS REGION_CODE_RIAU,
    IFF(REGION_CODE='SULSEL',1,0)::FLOAT  AS REGION_CODE_SULSEL,
    IFF(REGION_CODE='SULUT',1,0)::FLOAT   AS REGION_CODE_SULUT,
    IFF(REGION_CODE='SUMSEL',1,0)::FLOAT  AS REGION_CODE_SUMSEL,
    IFF(REGION_CODE='SUMUT',1,0)::FLOAT   AS REGION_CODE_SUMUT,
    IFF(REGION_CODE='YOGYA',1,0)::FLOAT   AS REGION_CODE_YOGYA,
    AGE, MONTHLY_INCOME, NUM_ACTIVE_LOANS, NUM_CREDIT_CARDS, NUM_FINTECH_LOANS,
    NUM_BNPL_ACCOUNTS, NUM_LENDERS, NUM_INQUIRIES_3M, NUM_INQUIRIES_12M, MAX_DPD_12M,
    MAX_DPD_24M, NUM_LATE_PMT_12M, OLDEST_ACCT_AGE_MONTHS, AVG_ACCT_AGE_MONTHS,
    TOTAL_OUTSTANDING, TOTAL_CREDIT_LIMIT, CREDIT_UTILIZATION, MONTHLY_INSTALLMENT,
    KOL_STATUS, DEPENDENTS, CC_OUTSTANDING, KTA_OUTSTANDING, KPR_OUTSTANDING,
    CC_UTIL, KTA_UTIL, PAYMENT_RATIO_3M, PAYMENT_RATIO_12M, ONTIME_RATIO_12M,
    REVOLVING_RATIO,
    MONTHLY_INSTALLMENT / (CASE WHEN MONTHLY_INCOME = 0 THEN 1 ELSE MONTHLY_INCOME END) AS DTI_RATIO
FROM SUBJECT_FEATURES;

-- 1) Preview scoring 1000 baris langsung dari SQL (warehouse inference)
WITH scored AS (
  SELECT
    SUBJECT_ID,
    CLIK_PD_MODEL!PREDICT_PROBA(
      GENDER_F, GENDER_M, EMPLOYMENT_TYPE_FREELANCE, EMPLOYMENT_TYPE_KARYAWAN, EMPLOYMENT_TYPE_PNS,
      EMPLOYMENT_TYPE_PROFESIONAL, EMPLOYMENT_TYPE_WIRASWASTA, EDUCATION_D3, EDUCATION_S1, EDUCATION_S2,
      EDUCATION_SD, EDUCATION_SMA, REGION_CODE_BALI, REGION_CODE_BANTEN, REGION_CODE_DKI, REGION_CODE_JABAR,
      REGION_CODE_JATENG, REGION_CODE_JATIM, REGION_CODE_KALBAR, REGION_CODE_KALTIM, REGION_CODE_LAMPUNG,
      REGION_CODE_MALUKU, REGION_CODE_NTB, REGION_CODE_PAPUA, REGION_CODE_RIAU, REGION_CODE_SULSEL,
      REGION_CODE_SULUT, REGION_CODE_SUMSEL, REGION_CODE_SUMUT, REGION_CODE_YOGYA, AGE, MONTHLY_INCOME,
      NUM_ACTIVE_LOANS, NUM_CREDIT_CARDS, NUM_FINTECH_LOANS, NUM_BNPL_ACCOUNTS, NUM_LENDERS, NUM_INQUIRIES_3M,
      NUM_INQUIRIES_12M, MAX_DPD_12M, MAX_DPD_24M, NUM_LATE_PMT_12M, OLDEST_ACCT_AGE_MONTHS, AVG_ACCT_AGE_MONTHS,
      TOTAL_OUTSTANDING, TOTAL_CREDIT_LIMIT, CREDIT_UTILIZATION, MONTHLY_INSTALLMENT, KOL_STATUS, DEPENDENTS,
      CC_OUTSTANDING, KTA_OUTSTANDING, KPR_OUTSTANDING, CC_UTIL, KTA_UTIL, PAYMENT_RATIO_3M, PAYMENT_RATIO_12M,
      ONTIME_RATIO_12M, REVOLVING_RATIO, DTI_RATIO
    ):"PREDICT_PROBA_1"::FLOAT AS pd_score
  FROM SUBJECT_FEATURES_ENCODED
  LIMIT 1000
)
SELECT
  SUBJECT_ID,
  ROUND(pd_score, 4) AS pd_probability,
  300 + ROUND(550 * (1 - pd_score)) AS credit_score,
  CASE
    WHEN pd_score < 0.10 THEN 'APPROVE'
    WHEN pd_score < 0.30 THEN 'REVIEW'
    ELSE 'REJECT'
  END AS decision
FROM scored;

-- 2) Batch scoring penuh: simpan hasil ke tabel SCORE_RESULTS
CREATE OR REPLACE TABLE SCORE_RESULTS AS
WITH scored AS (
  SELECT
    SUBJECT_ID,
    CLIK_PD_MODEL!PREDICT_PROBA(
      GENDER_F, GENDER_M, EMPLOYMENT_TYPE_FREELANCE, EMPLOYMENT_TYPE_KARYAWAN, EMPLOYMENT_TYPE_PNS,
      EMPLOYMENT_TYPE_PROFESIONAL, EMPLOYMENT_TYPE_WIRASWASTA, EDUCATION_D3, EDUCATION_S1, EDUCATION_S2,
      EDUCATION_SD, EDUCATION_SMA, REGION_CODE_BALI, REGION_CODE_BANTEN, REGION_CODE_DKI, REGION_CODE_JABAR,
      REGION_CODE_JATENG, REGION_CODE_JATIM, REGION_CODE_KALBAR, REGION_CODE_KALTIM, REGION_CODE_LAMPUNG,
      REGION_CODE_MALUKU, REGION_CODE_NTB, REGION_CODE_PAPUA, REGION_CODE_RIAU, REGION_CODE_SULSEL,
      REGION_CODE_SULUT, REGION_CODE_SUMSEL, REGION_CODE_SUMUT, REGION_CODE_YOGYA, AGE, MONTHLY_INCOME,
      NUM_ACTIVE_LOANS, NUM_CREDIT_CARDS, NUM_FINTECH_LOANS, NUM_BNPL_ACCOUNTS, NUM_LENDERS, NUM_INQUIRIES_3M,
      NUM_INQUIRIES_12M, MAX_DPD_12M, MAX_DPD_24M, NUM_LATE_PMT_12M, OLDEST_ACCT_AGE_MONTHS, AVG_ACCT_AGE_MONTHS,
      TOTAL_OUTSTANDING, TOTAL_CREDIT_LIMIT, CREDIT_UTILIZATION, MONTHLY_INSTALLMENT, KOL_STATUS, DEPENDENTS,
      CC_OUTSTANDING, KTA_OUTSTANDING, KPR_OUTSTANDING, CC_UTIL, KTA_UTIL, PAYMENT_RATIO_3M, PAYMENT_RATIO_12M,
      ONTIME_RATIO_12M, REVOLVING_RATIO, DTI_RATIO
    ):"PREDICT_PROBA_1"::FLOAT AS pd_probability
  FROM SUBJECT_FEATURES_ENCODED
)
SELECT
  SUBJECT_ID,
  pd_probability,
  300 + ROUND(550 * (1 - pd_probability)) AS credit_score,
  CASE
    WHEN pd_probability < 0.10 THEN 'APPROVE'
    WHEN pd_probability < 0.30 THEN 'REVIEW'
    ELSE 'REJECT'
  END AS decision,
  CURRENT_TIMESTAMP() AS scored_at,
  'V2_SNOWPARK_ML' AS model_version
FROM scored;

-- 3) Ringkasan distribusi keputusan
SELECT decision, COUNT(*) AS cnt, ROUND(AVG(pd_probability),4) AS avg_pd
FROM SCORE_RESULTS GROUP BY decision ORDER BY avg_pd;
